[package]
name = "lsh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.47", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rustyline = "17.0.2"

[dev-dependencies]
serial_test = "3"
tempfile = "3"
